# Load the required gems/libraries.
require 'rubygems'
require 'bundler/setup'
require 'active_record'
require 'sqlite3'
require 'logger'
require 'json'
require 'net/http'

require_relative 'ar'
# Load Rails environment
require_relative 'config/environment'
# Load the ActiveRecord::Base objects for Pokemon and Type tables.
require_relative 'app/models/pokemon.rb'
require_relative 'app/models/type.rb'

# Establish the connection to the SQLite3 database.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'db/development.sqlite3')

# For debugging purposes, comment out if you don't wish to see the SQL generated by ActiveRecord.
ActiveRecord::Base.logger = Logger.new(STDOUT)